algae = []

insect = []

amphibians = ['Chinese Giant Salamander/  ','  Great crested Newt / / ','  Sagalla caecilian / ','  Purple frog / ','  Lmaur leaf Frog / ','  Golden arrow poison frog  / ','  common toad /  ','  Forest tree frog / ','  Axoloti / ','  Lake Titicaca Frog /  ','  Mallorcan miswife toad / ','  Smooth Newt  / ','  Leopard Toad /  ','  African Reed Frog / / ','  Dyeing Poison Frog /  ',' Golden Toad / ',' Natterjack Toad/ / ',' Tomato Frog / ',' Pool Frog / ',' Japanese Giant Salamander  / ',' Goliath Frog / / ',' Gardiners Tree frog / ',' Cave Salamander / ',' Arabian Toad /',' Corroboree Frog / ',' African Giant Toad / ',' Golden Frog  / ',' Rabb\'s Fringe Limbed tree frog / ',' Sunset Frog /',' Banana Frog / ',' African Wart frog / / ',' Darwin\'s frog / ',' Gold Striped Salamander / ',' Lehmann\'s oison Frog / ',' North American fire Salamander  / ',' Water frog /  ',' Southern Gastric Brooding frog / ',' Granilar Poison Frog  / ',' Desert Rain frog / ',' Calnarachi Poison Frog / ',' Gray Wood Frog /']


birds = [ 'King Pengwin/ ',' African Grey parrot/ ',' Kakapo/ ',' Andean Flamingo/ ',' Japanese Crane/ ',' Long eared owl/ ',' Ostrich/ ',' Puffin/ ',' Southern Cassowary/ ',' Bald Eagle/ ',' Kingfisher/ ',' Emperor Pengwin/ ',' Secretarybied/ ',' Wilson\'s Bird-of-Paradice/ ',' California Condor/ ',' Blue Cheeked bee-eater/ ',' Imperial eagle/ ',' Albert\'s Lyrebird/ ',' Great Spotted Kiwi/ ',' Green Peafowl/ ',' Phillippine Eagle/ ',' Mallard/ ',' Hyacinth Macaw/ ',' Galapagos Pengwin/ ',' Burrowing owl/ ',' Bee Hummingbird/ ',' Goldfinch/ ',' Adelie pengwin/ ',' Osprey/ ',' Blue Bird-of-paradice/ ',' Lappet-Faced Vulture/ ',' Americal Kestrel/ ',' Robin/ ',' Snowy Own/ ',' Fire manned bowerbird/ ',' Blackbird/ ',' Greater Soptted owl/ ',' Large Ground Finch/ ',' Macaroni Pengwin/ ',' Red Kite/ ',' Royal Pengwin/ ',' Barn Owl/ ',' Cuckoo/ ',' Emu/ ',' Peregrine/ ',' Spix\'s macaw/ ',' Three wattled Bellbird/ ',' Golden Eagle/ ',' Eurasian Hobby/ ',' Henderson Petrel/']


fish = ['Great White Shark/ ','Coelacanth/ ','Leafy Seadragon/ ','Queen Triggerfish/ ','Southern Bluefin Tuna/ ','Whale Shark/ ','Spotted Handfish/ ','Pygmy Seahorse/ ','Frilled Shark/ ','Basking Shark/ ','Commom eel/ ','Hummped Parrotfish/ ','Manta ray/ ','Pike/ ','Great Hammerhead/ ','Sunfish/ ','Atlantic Salmon/ ','Bowmouth Guratfish/ ','Oceanic Whitetip Shark/ ','Smalltooth Sawfish/ ','Yellowfin Tuna/ ','Tiger Shark/ ','yangtze Sturgeon/ ','Humphead Wrasse/ ','Common Seahorse/ ','Leopard Shark/ ','River lamprey/ ','Swordfish/ ','Aramaima/ ','Ribbontaled Stingray/ ','Red Bellied Piranha/ ','Shortfin mako/ ','Beluga/ ','Angelfish/ ','Megamouth Shark/ ','Three-Spined Stickleback/ ','Spotted Eagle ray/ ','Backflip Reef shark/ ','Albacore Tuna/ ','Porbeagle/ ','Sharptooth lemon Shark/ ','Rainbow Parrotfish/ ','Pacific angel Shark/ ','Big belly Sea Horse/ ','Goliath Grouper/ ','Salmon Shark/ ','Common carp/ ','Thresher Shark/ ','Bull Shark/']


invet_terr = ['Coconut Crab/ ','Apolio Butterfly/ ','Emperor Scorpion/ ','Garden Snail/ ','Monarch Butterfly/ ','large Garden Bumblebee/ ','Giant Fresh water Crayfish/ ','Common Field grasshopper/ ','Dracula Ant/ ','Honey bee/ ','Mexican Rustleg Tarantula/ ','Yabble Crayfish/ ','Seven Spot Ladybird/ ','Mexican Redknee Tarantula/ ','Garden Spider/ ','Common Green Darner/ ','Earthworm/ ','Queen Alexandrea\'s birdwing/ ','Stag Beetle/ ','Death Watch Bettle/ ','common wasp/ ','Green tiger Beetle/ ','Adonis blue/ ','Medicinal leach/ ','Purse-web Spider/ ','Trumpet-mouthed Hunter snail/ ','Emperor month/ ','Cinnabar Moth/ ','Giant Tube worm/ ','Oil Beetle/ ','Ladybird Spider/ ','Water Scorpion/ ','Peppered Moth/ ','Leaf cutter Ant/ ','Crab Spider/ ','Black Widow Spider/ ','Common garden Slug/ ','Horse-Fly/ ','Six-Spot Burnet moth/ ','Zebra Spider/ ','Peacock butterfly/ ','Common Woodlouse/ ','Matrona/ ','Great Mond Snail/ ','Nurdery-Web Spider/ ','Water Spider/ ','pill woodlouse/ ','House Spider/']


invet_fresh = ['Acorne Weevil/ ',' Actinella/ ',' Actinella/ ',' Actinella/ ',' Acuminate Snake tail/ ',' Adonis Blue/ ',' African Babul blue/ ',' African Giant Swllow tail/ ',' Agrias/ ',' Alabama Cave Crayfish/ ',' Alabama cave Shrimp/ ',' Alabama Lampmussel/ ',' Alcorn Large Blue/ ',' Aldabra Bandad Snail/ ',' Alderfly/ ',' Algerian Clubtail/ ',' Ailocharopa/ ',' Alpine Emerals/ ',' Alphine Zypher Blue/']


invet_marine = ['Giant Clam/ ',' Compas Jellyfish/ ',' Elkhorn Coral/ ',' Mushroom Coral/ ',' Purple Sea Urchin/ ',' Horseshoe crab/ ',' Flowerpot corals/ ',' common Lobster/ ',' Beaslet Anemone/ ',' Cauliflower Corals/ ',' Nautilus/ ',' Staghorn coral/ ',' Common Octopus/ ',' Editible Eea Urchine/ ',' native oyster/ ',' Lace coral/ ',' Sea Lemon/ ',' Velvet Swimming Crab/ ',' Common Cuttlefish/ ',' Acorn Barnacle/ ',' Common Starfish/ ',' Fire Corals/ ',' Lugworm/ ',' Sea Slater/ ',' North Pacific Giant Octopus/ ',' Cuban Cave Shrimp/ ',' Common Jellyfish/ ',' Black Abalone/ ',' Elegance Coral/ ',' Humboldt Squid/ ',' Razor Shell/ ',' Goose Barnicale/ ',' Closed Brain Coral/ ',' Common Shore Crab/ ',' Southern Blue ringed Octopus/ ',' tall Sea Pen/ ',' Jewwl Anemone/ ',' Flat Periwinkle/ ',' Black Corals/ ',' Common Limpet/ ',' Ctenella Coral/ ',' masked crab/ ',' Pavona Coral/ ',' Sea Spider/ ',' Finger Coral/ ',' Common Whelk/ ',' Curled octopuss/ ',' Common Hermit Crab/ ',' Red Coral/ ',' Common Cockle/']


mammals = ['Tiger/ ',' African Elephant/ ',' Blue Whale/ ',' Born orangutan/ ',' Giant Panda/ ',' Brown Bear/ ',' Lion/ ',' Orca/ ',' Giraffe/ ',' Polar bear/ ',' Western Gorilla/ ',' Black Rhinoceros/ ',' African Wild Dog/ ',' Bottlenose Dolphin/ ',' Snow Leopard/ ',' Hippopotamus/ ',' Hunpback Whale/ ',' Koala/ ',' Jaguar/ ',' Asian Elephant/ ',' Aardvark/ ',' Red fox/ ',' Moose/ ',' Grey Wolf/ ',' Chimpanzee/ ',' Cheetah/ ',' Puma/ ',' Ring tailed Lemur/ ',' Giant Armadillo/ ',' Sperm Whale/ ',' Iberian Lynx/ ',' Aye-Aye/ ',' Brown Hyaena/ ',' Coyote/ ',' Grevy\'s Zebra/ ',' Pygmy three toes Sloth/ ',' Red Panda/ ',' Wolverine/ ',' Saola/ ',' Red Wold/ ',' Przwalski\'s Horse/ ',' Narwal/ ',' Clowded Leopard/ ',' Bonobo/ ',' Black footed ferret/ ',' Caracal/ ',' Black Flying fox/ ',' African wild Ass/ ',' Common Vampire bat/ ',' Fishing Cat/']


plants = ['Venis Flytrap/ ',' Coco-de-mer/ ',' Fanged Pitcher Plant/ ',' Giant Sequoia/ ',' King Protea/ ',' St Helena Olive/ ',' Dragon Tree/ ',' Monkey Puzzle/ ',' tesesee Purple cone Flower/ ',' Flame Tree/ ',' Harlequin Flower/ ',' Raffesia/ ',' Lava Cactus/ ',' Sessile Oak/ ',' Titan Arum/ ',' Azobe/ ',' Madagascar Pitcher Plant/ ',' Greater Cobera lily/ ',' Ash/ ',' Bluebell/ ',' White lauan/ ',' Black Ebony/ ',' Daisy/ ',' Green Pitcher Plant/ ',' Okoume/ ',' Red Campion/ ',' Horse Chestnut/ ',' Common Dandelion/ ',' Silver Birtch/ ',' Fairy Slipper/ ',' Brambie/ ',' Mulanje Cedar/ ',' Red Lauan/ ',' Pedunculate Oak/ ',' Hawthorn/ ',' Enteromorpha/ ',' Common Butterwort/ ',' Brazile-Nut tree/ ',' Brazilian Rosewood/ ',' Jellyfish Tree/ ',' Lady\'s Slipper orchis/ ',' Blackthorn/ ',' Cow parsley/ ',' Bladder Wrack/ ',' Sycamore/ ',' Pennyroyal/ ',' Bayashibe/ ',' Common Holly/ ',' Bell Heather/ ',' Common Chickweed/']


reptials = ['Komodo Dragon/ ',' Arabian Horned Viper/ ',' Black Calman/ ',' Galapagos marine Iguana/ ',' Hawksbill turtle/ ',' Parson\'s Chameleon/ ',' Western Diaimond- backed Rattlesnake/ ',' Green Iguana/ ',' Loggerhead turtle/ ',' Radiated Tortoise/ ',' Nile Cockodile/ ',' Short-Horned Chameleon/ ',' Adder/ ',' Aldabra Giant Tortoise/ ',' Sand Lizard/ ',' American Alligator/ ',' Yellow Sea Snake/ ',' Western Swamp turtle/ ',' Sal-Fin Lizard/ ',' Grass Snake/ ',' Cuban Crocodile/ ',' Egyption Spiny Taled lizard/ ',' Alagator Snapping turtle/ ',' Galapagos Giant Tortoise/ ',' Leatherback Turtle/ ',' Slow Worm/ ',' Tiger Chameleon/ ',' King Cobera/ ',' Specaled Calaman/ ',' Aruba Island Rattlesnake/ ',' African Rock Python/ ',' Gharial/ ',' Madagascar Tre Boa/ ',' Saltwater Crocodile/ ',' Fiji Banded Iguana/ ',' Satanic Leafed-Tailed Gecko/ ',' Gila monster/ ',' Olive Ridley Turtle/ ',' Phillippine crocodile/ ',' Viviparous Lizard/ ',' Big-Headed Turtle/ ',' Africal Spurred Tortiose/ ',' Green Anaconda/ ',' Namaqua Chameleon/ ',' Afghan Tortoise/ ',' Beaked Sea Snake/ ',' Orinoco Crockdile/ ',' Smooth Snake/ ',' African Burrowing Python/ ',' Siamease Crocodile/']



